version: '1'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"

    # Expose the dynamic port range for P2P file sharing
    expose:
      - "49152-65535:49152-65535"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend